source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SpriteKitEasingSwift_Example', :exclusive => true do
  pod 'SpriteKitEasingSwift', :path => '../'
end

target 'SpriteKitEasingSwift_Tests', :exclusive => true do
  pod 'SpriteKitEasingSwift', :path => '../'

  
end
