use_frameworks!

target 'SpriteKitEasingSwift_Example' do
  pod 'SpriteKitEasingSwift', :path => '../'

  target 'SpriteKitEasingSwift_Tests' do
    inherit! :search_paths
    pod 'Quick'
  	pod 'Nimble'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
