use_frameworks!

target 'SpriteKitEasingSwift_Example' do
  pod 'SpriteKitEasingSwift', :path => '../'

  target 'SpriteKitEasingSwift_Tests' do
    inherit! :search_paths
    pod 'Quick'
  	pod 'Nimble'
  end
end
